create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null,
  display_name text not null default 'Administrator',
  role text not null default 'admin' check (role in ('admin','manager','viewer')),
  created_at timestamptz not null default now()
);

create table if not exists public.members (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text,
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  member_id bigint references public.members(id) on delete set null,
  transaction_date date not null default current_date,
  transaction_time time,
  category text not null default 'bill' check (category in ('bill','coin')),
  type text not null check (type in ('debit','credit')),
  bill_name text not null,
  amount numeric(12,2) not null check (amount >= 0),
  notes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Existing DB upgrades (safe to re-run)
alter table public.transactions add column if not exists transaction_time time;
alter table public.transactions add column if not exists category text;
update public.transactions set category = 'bill' where category is null;
alter table public.transactions alter column category set default 'bill';
alter table public.transactions alter column category set not null;

create index if not exists transactions_date_idx on public.transactions(transaction_date);
create index if not exists transactions_member_idx on public.transactions(member_id);
create index if not exists transactions_type_idx on public.transactions(type);
create index if not exists transactions_category_idx on public.transactions(category);

alter table public.profiles enable row level security;
alter table public.members enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "authenticated profiles" on public.profiles;
create policy "authenticated profiles" on public.profiles
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated members" on public.members;
create policy "authenticated members" on public.members
for all to authenticated using (true) with check (true);

drop policy if exists "authenticated transactions" on public.transactions;
create policy "authenticated transactions" on public.transactions
for all to authenticated using (true) with check (true);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists transactions_updated_at on public.transactions;
create trigger transactions_updated_at
before update on public.transactions
for each row execute function public.set_updated_at();

-- After creating Auth user, run:
-- insert into public.profiles (id, username, display_name, role)
-- values ('AUTH_USER_UUID', 'admin', 'Administrator', 'admin')
-- on conflict (id) do update set username='admin', role='admin';
